# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c2oproduct',
            name='colour',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
