# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2OSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('in_stock', models.BooleanField()),
                ('sku_code', models.CharField(max_length=255)),
                ('colour', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
            ],
        ),
    ]
