# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_c2oproduct_etsy_listing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooVariantSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='c2oproduct',
            name='woo_listing_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='woovariantsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woo_skus', to='catalogue.C2OProduct'),
        ),
    ]
