# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C2OOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luma_id', models.CharField(max_length=255, unique=True)),
                ('c2o_id', models.CharField(blank=True, max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('request_json', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('SENT', 'SENT'), ('INVALID', 'INVALID'), ('DISPATCHED', 'DISPATCHED')], default='NEW', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('delivery_method', models.CharField(choices=[('standard', 'standard'), ('4day', '4day'), ('express', 'express')], default='standard', max_length=30)),
                ('individual_bags', models.BooleanField(default=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_telephone', models.CharField(blank=True, max_length=255)),
                ('address_delivery_name', models.CharField(blank=True, max_length=255)),
                ('address_company_name', models.CharField(blank=True, max_length=255)),
                ('address_address_line_1', models.CharField(max_length=255)),
                ('address_address_line_2', models.CharField(blank=True, max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_county', models.CharField(blank=True, max_length=255)),
                ('address_postcode', models.CharField(max_length=255)),
                ('address_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='C2OOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('c2o_sku', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.C2OOrder')),
            ],
        ),
    ]
