# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2oorder',
            name='store_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='c2oorder',
            name='store_platform',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
