# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2oorder',
            name='response_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='c2oorderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
