# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160115_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2oorder',
            name='c2o_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
