# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_c2oorder_c2o_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='c2oorder',
            name='shipped_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='c2oorder',
            name='tracking_link',
            field=models.TextField(blank=True),
        ),
    ]
